### ISSUE TITLE
Support for reading image from buffer?

### ISSUE THREAD

**Issue by ganego** [james-see/iptcinfo3#13]
Hi, sometimes I need IPTC info not from a file on disk but from a file inside an archive. For this reason I read the image from the archive into memory.  
I'm using piexif to get exif from the image and it works with a bytestring/buffer. Any plans to implement this feature to iptcinfo3?

Thank you

**Comment by nealmcb** [comment]
A workaround would seem to be to use `BytesIO`, but that fails in a different way for me.

```
import BytesIO
# My goal is get the actual photo data out of memory, from a `mailbox` file. Here I just read it from a file to set things up.
photo = BytesIO(open("photo.jpg", "rb").read()
info = IPTCInfo(photo)
info['caption/abstract'] = "test caption"
info.save_as('/tmp/photo-with-tags')
```

**Comment by TomAnthony** [comment]
I am having the same issue as @nealmcb. Did you happen to find any workaround?

**Comment by nealmcb** [comment]
@TomAnthony I ended up saving the buffer to a file so I could run this stuff.  I guess that for efficiency, it might be useful to use a memory-mapped file system like /dev/shm.

**Comment by TomAnthony** [comment]
Thanks @nealmcb. I did a similar workaround for now too. I think addressing this would be useful to those that follow (and for efficiency).

**Comment by jamesacampbell** [comment]
@TomAnthony @nealmcb any suggestions on updating this? Finally looking back at this.

**Comment by nealmcb** [comment]
Thanks, James! I don't know enough about the internals, but my first question from above remains: why does it (seem to be) seeking the file after closing it?

**Comment by TomAnthony** [comment]
Yeah, I am in the same boat as @nealmcb. I don't know why it should be seeking it after closing. For me performance wasn't a priority so I just worked around it as per @nealmcb 's suggestion above.

**Comment by jamesacampbell** [comment]
@TomAnthony @nealmcb it looks like there is a function that reads raw already. Adding in the ability to chunk in via a method from BytesIO as a build in method inside the IptcInfo class should not be _too_ difficult. Famous last words lol.

**Comment by jamesacampbell** [comment]
@nealmcb I believe it was falling down throwing the error because you tried to sidestep and create the read-in photo object from BytesIO beforehand, when it is expecting a file object there. The error is just erroneous. It should say something like "not a file object to process" or something. That is a guess based on not delving deep into the functions.
