### ISSUE TITLE
Not recognizing resident IPTC data

### ISSUE THREAD

**Issue by skcsinc** [james-see/iptcinfo3#16]
For some reason some images I'm testing with that already have some IPTC data are not loading with that data being recognized. I have to force load it as if there is no pre-existing data.

Once force loaded I can add additional IPTC data to the image but I cannot change any of the fields already there. If I load the same image into Photoshop and edit the info there, all is good.

Any idea what might be happening here?

**Comment by jamesacampbell** [comment]
@skcsinc can you provide me with an example. Sorry for the late reply to this, I am just seeing it now.

**Comment by james-see** [comment]
closed, no response.
