### ISSUE TITLE
Support for new Google IPTC Tags

### ISSUE THREAD

**Issue by ckdecember** [james-see/iptcinfo3#20]
Hi there!  Thanks for the excellent work on this software!  Apologies in advance if I am not using the software correctly, but does it support the new IPTC tags that google will now support and display in their search?

https://www.iptc.org/std-dev/photometadata/examples/google-licensable/example-page1.html

https://getpmd.iptc.org/getpmd/html/isearch1/ipmd/?imgurl=https://www.iptc.org/std-dev/photometadata/examples/google-licensable/images/IPTC-GoogleImgSrcPmd_testimg01.jpg

I tried to use iptcinfo3 to read the file and while it does get a lot of metadata, it does not get all of the fields such as Licensor or Web Statement of Rights.

I am assuming I can't add a new field at will as it seems to throw a "key not found" error.  (I'm also going to take a wild guess it has to fit the proper format/location in IPTC).  If I am in error, I am sorry and ask how I can add a new IPTC field?

Thanks again for the work!

**Comment by martimpassos** [comment]
+1, I'm trying to use to write Artwork related metadata (Title, Description, Date Circa, Inventory Number, URL), as well as Location Shown tags. Support for [this](https://iptc.org/std/photometadata/documentation/userguide/#_administration_and_commissioning_details) structure would be really great!

**Comment by ckdecember** [comment]
I ended up using exiftool by Phil Harvey since it apparently seems to be a "standard" in metadata tagging.

Yes, exiftool is Perl.  Yes pyexiftool is a mere wrapper.  But darnnit, it works.  :)

**Comment by jamesacampbell** [comment]
@ckdecember so with exiftool you get iptc tags and exif data tags? Id love to chat about this if you have time. Are you on signal or google meet to chat on feedback for your use case?

**Comment by jamesacampbell** [comment]
@ckdecember I am looking into this now to try to repeat the failture of not getting all of the IPTC tags that are available from the metadata.

**Comment by martimpassos** [comment]
if I may comment on this, exiftool also doesn't seem to have support for Artwork/Object related fields, although it has a wider range of tags available. But yes it is able to read/write IPTC and other tags, despite it's name.

**Comment by james-see** [comment]
Not working on this unless someone sponsors this repo.
