### ISSUE TITLE
TypeError: ord() expected string of length 1, but NoneType found

### ISSUE THREAD

**Issue by fishcode16** [james-see/iptcinfo3#21]
Sample Image file from Meetup.com
https://secure.meetupstatic.com/photos/event/5/7/3/9/highres_489862329.jpeg

using python 3.8.0 and latest version of IPTCInfo3 2.1.4
work with all of the images I have so far, except those from meetup.com.

Please advise. 

Thanks

script:
```
f = "highres_489862329.jpeg"
info = IPTCInfo(f, force=True)
info.save()
```

output:
```
Marker scan hit start of image data
Traceback (most recent call last):
  File "C:\TEST iptcinfo\iptc.py", line 11, in <module>
    info.save()
  File "C:\Users\random-user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\iptcinfo3.py", line 627, in save
    return self.save_as(self._filename, options)
  File "C:\Users\random-user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\iptcinfo3.py", line 636, in save_as
    jpeg_parts = jpeg_collect_file_parts(fh)
  File "C:\Users\random-user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\iptcinfo3.py", line 265, in jpeg_collect_file_parts
    marker = ord(jpeg_next_marker(fh))
TypeError: ord() expected string of length 2, but NoneType found
```

**Comment by fishcode16** [comment]
![highres_489862329](https://user-images.githubusercontent.com/66345907/85926014-d5534780-b8ce-11ea-86bc-ecda736d1e6d.jpeg)

**Comment by petrst** [comment]
Hi,
same error here:
```
  File "annotate.py", line 33, in update_iptc
    info.save()
  File "c:\Users\psturc\Downloads\gallery-dl\venv\lib\site-packages\iptcinfo3.py", line 627, in save
    return self.save_as(self._filename, options)
  File "c:\Users\psturc\Downloads\gallery-dl\venv\lib\site-packages\iptcinfo3.py", line 636, in save_as
    jpeg_parts = jpeg_collect_file_parts(fh)
  File "c:\Users\psturc\Downloads\gallery-dl\venv\lib\site-packages\iptcinfo3.py", line 265, in jpeg_collect_file_parts
    marker = ord(jpeg_next_marker(fh))
TypeError: ord() expected string of length 1, but NoneType found
```
[
![flickr_12203912545](https://user-images.githubusercontent.com/1809119/106739556-954d0380-6619-11eb-9f51-9267728ed2af.jpg)
](url)

Image attached.

**Comment by jamesacampbell** [comment]
@petrst I was able to use it fine:

```
import iptcinfo3
info = iptcinfo3.IPTCInfo("/Users/jc/Downloads/test.jpg")
print(info)
```

resulting in:

```
$ python3 iptcinfotest1.py
WARNING: problems with charset recognition (b'\x1b')
charset:        None
data:   {'supplemental category': [], 'keywords': [], 'contact': [], 'nonstandard_230': b'https://flickr.com/e/6dOflm61YZeqanFe9cs4s8VSwPHBhwQ4YERykdKJl5o%3D'}
```

**Comment by jamesacampbell** [comment]
@petrst please let me know what you find out so I can close out this issue. Thanks

**Comment by petrst** [comment]
@jamesacampbell  - the problem appears only when you call `info.save()`. try following:

```
import iptcinfo3
info = iptcinfo3.IPTCInfo('test.jpg')
print(info)
info['headline']=['My headline']
info.save()
```

I did investigate further. It looks like the attached JPEG doesn't have neither APP0 nor APP1 markers. Is it still valid JFIF file? Guess not. Though the JPEG is downloaded from Flickr 🤔

**Comment by jamesacampbell** [comment]
> @jamesacampbell - the problem appears only when you call `info.save()`. try following:
> 
> ```
> import iptcinfo3
> info = iptcinfo3.IPTCInfo('test.jpg')
> print(info)
> info['headline']=['My headline']
> info.save()
> ```
> 
> I did investigate further. It looks like the attached JPEG doesn't have neither APP0 nor APP1 markers. Is it still valid JFIF file? Guess not. Though the JPEG is downloaded from Flickr 🤔

Yeah that is weird. @petrst how do you think we should handle this? Should we try to ignore that it doesn't find markers and tries to still write out? Warn the user and move on, or ask the user to convert the file to a png and try again? I am open to suggestions.

**Comment by achristlex** [comment]
Was this ever solved? I am not sure how to either get around the error / continuing a loop since the file isn't markedly different in any particular way and since I'm tagging thousands of files, individually identifying the errored ones isn't viable.

As noted, it only happens when attempting to info.save().

**Comment by ammacdonald3** [comment]
Until a different fix is implemented, I was able to avoid this issue by using the Pillow module to convert to RGB then JPG again before running the IPTCInfo3 code.  In the example below, "full_path" is a variable I'm using representing the file path.

`from PIL import Image`
`im = Image.open(full_path)`
`rgb_im = im.convert('RGB')`
`updated_path = full_path + ".jpg"`
`rgb_im.save(full_path)`

**Comment by james-see** [comment]
@ammacdonald3 I would follow this pre-processing to standardize in a large pipeline anyway. IPTCInfo is expecting something, and you should provide it what it expects. Having IPTCInfo do any more than that or try to figure it out is a topic for debate, but not here at this time.
