### ISSUE TITLE
Headline truncation on comma

### ISSUE THREAD

**Issue by VBykov-HORIS** [james-see/iptcinfo3#33]
Headline field truncated to :  b'Tasty,Salad,With,Brussels,Sprouts,In,Bowl,Isolated,On,White,'
Should be: Tasty salad with Brussels sprouts in bowl isolated on white, top view
![shutterstock_1686846844](https://user-images.githubusercontent.com/52575485/114556012-f1af4d80-9c70-11eb-808f-0e010ebc9291.jpg)

**Comment by adityamulik** [comment]
![image](https://user-images.githubusercontent.com/10626835/127778640-2e37b1bc-3ac2-4a74-a0dc-e71138cbb4f2.png)

Can you try again?

**Comment by james-see** [comment]
Closing, the example displayed works.
